### ISSUE TITLE
Fix statistic requirement

### ISSUE THREAD

**Issue by Davod0** [Davod0/App-Development-Household-Application#151]

**Comment by mrKornelius** [comment]
Detta ska göras

- [x]  Det ska finnas en statistikvy över ”nuvarande vecka”. *
- [ ] Det ska finnas en statistikvy över ”förra vecka”.
- [ ] Det ska finnas en statistikvy över ”förra månaden”.
- [ ] Om det inte finns statistik för en av vyerna ska den vyn inte visas.
