### ISSUE TITLE
Make the buttons on Dina hushåll navigate to their destinated screens

### ISSUE THREAD

**Issue by TeenyTinyTurtle123** [Davod0/App-Development-Household-Application#24]
OBS! Gå med i hushåll och Skapa hushåll skärmar måste ha skapats innan denna kan göras

- [x] #16  
- [x] #11  
- [x] #40 

![Image](https://github.com/user-attachments/assets/ab393a9c-a207-4f6c-9e8a-3a306569cc5f)

När man klickar på knapparna ska man navigeras till respektive skärm

**Comment by mrKornelius** [comment]
kanske kan användas till "ytorna"
https://callstack.github.io/react-native-paper/docs/components/Surface
