### ISSUE TITLE
Create Profile Button Component

### ISSUE THREAD

**Issue by TeenyTinyTurtle123** [Davod0/App-Development-Household-Application#27]
![Image](https://github.com/user-attachments/assets/666fe54d-55a8-4dd5-9d14-21de62b200be)

Skapa en knapp som tar en till son profil sida

**Comment by mrKornelius** [comment]
På vilken screen?
Borde väl funka med en ikon?

**Comment by mrKornelius** [comment]
#47

**Comment by mrKornelius** [comment]
aha nu fattar jag 👍🏼
