### ISSUE TITLE
Create mocked data in data.ts

### ISSUE THREAD

**Issue by Alireza177** [Davod0/App-Development-Household-Application#9]

**Comment by Toxex** [comment]
Also type everything up

**Comment by mrKornelius** [comment]
screenshot på databasen:
![Image](https://github.com/user-attachments/assets/95ef26fd-cfdb-43b9-90e8-fd27128f2530)

För typerna tänker jag att du kan sätta string på allt utom 
- isOwner/isAllowed/isArchived som ska vara bool
- weight/frequency number
- dateDone kan vara av typen Date
- icon tänker jag kan vara `type Icon = 'fox' | 'pig' | 'frog' | ... `
- color tänker jag kan vara en `type Color = 'orange' | 'pink' | 'green' | ... `
